// <auto-generated />
using System;
using HRPortal.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRPortal.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260304094659_CreateHrAdminTable")]
    partial class CreateHrAdminTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HRPortal.API.Models.EmployeeAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentArea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_area");

                    b.Property<string>("CurrentCity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_city");

                    b.Property<string>("CurrentCountry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_country");

                    b.Property<string>("CurrentDoorNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_door_no");

                    b.Property<string>("CurrentPincode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_pincode");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_state");

                    b.Property<string>("CurrentStreet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_street");

                    b.Property<int>("EmpId")
                        .HasColumnType("integer")
                        .HasColumnName("emp_id");

                    b.Property<string>("PermanentArea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permanent_area");

                    b.Property<string>("PermanentCity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permanent_city");

                    b.Property<string>("PermanentCountry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permanent_country");

                    b.Property<string>("PermanentDoorNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permanent_door_no");

                    b.Property<string>("PermanentPincode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permanent_pincode");

                    b.Property<string>("PermanentState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permanent_state");

                    b.Property<string>("PermanentStreet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permanent_street");

                    b.HasKey("Id");

                    b.HasIndex("EmpId")
                        .IsUnique();

                    b.ToTable("employee_address");
                });

            modelBuilder.Entity("HRPortal.API.Models.EmployeeCompensation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountHolderName")
                        .HasColumnType("text")
                        .HasColumnName("account_holder_name");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text")
                        .HasColumnName("account_number");

                    b.Property<string>("AccountType")
                        .HasColumnType("text")
                        .HasColumnName("account_type");

                    b.Property<string>("BankName")
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<string>("Benefits")
                        .HasColumnType("text")
                        .HasColumnName("benefits");

                    b.Property<string>("BranchName")
                        .HasColumnType("text")
                        .HasColumnName("branch_name");

                    b.Property<int>("EmpId")
                        .HasColumnType("integer")
                        .HasColumnName("emp_id");

                    b.Property<string>("IFSCCode")
                        .HasColumnType("text")
                        .HasColumnName("ifsc_code");

                    b.Property<string>("TaxInfo")
                        .HasColumnType("text")
                        .HasColumnName("tax_info");

                    b.HasKey("Id");

                    b.HasIndex("EmpId")
                        .IsUnique();

                    b.ToTable("employee_compensation");
                });

            modelBuilder.Entity("HRPortal.API.Models.EmployeeDocuments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AddressProof")
                        .HasColumnType("bytea")
                        .HasColumnName("address_proof");

                    b.Property<byte[]>("AppointmentLetter")
                        .HasColumnType("bytea")
                        .HasColumnName("appointment_letter");

                    b.Property<byte[]>("BankAccountDetails")
                        .HasColumnType("bytea")
                        .HasColumnName("bank_account_details");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("EducationalCertificates")
                        .HasColumnType("bytea")
                        .HasColumnName("educational_certificates");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<byte[]>("ExperienceLetters")
                        .HasColumnType("bytea")
                        .HasColumnName("experience_letters");

                    b.Property<byte[]>("IdProof")
                        .HasColumnType("bytea")
                        .HasColumnName("id_proof");

                    b.Property<byte[]>("OfferLetter")
                        .HasColumnType("bytea")
                        .HasColumnName("offer_letter");

                    b.Property<byte[]>("PassportPhotos")
                        .HasColumnType("bytea")
                        .HasColumnName("passport_photos");

                    b.Property<byte[]>("Resume")
                        .HasColumnType("bytea")
                        .HasColumnName("resume");

                    b.Property<byte[]>("SignedNda")
                        .HasColumnType("bytea")
                        .HasColumnName("signed_nda");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("employee_documents");
                });

            modelBuilder.Entity("HRPortal.API.Models.EmployeeEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Certifications")
                        .HasColumnType("text")
                        .HasColumnName("certifications");

                    b.Property<string>("DegreeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("degree_name");

                    b.Property<int>("EmpId")
                        .HasColumnType("integer")
                        .HasColumnName("emp_id");

                    b.Property<string>("Percentage")
                        .HasColumnType("text")
                        .HasColumnName("percentage");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qualification");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("university");

                    b.Property<int>("YearOfPassing")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_passing");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.ToTable("employee_education");
                });

            modelBuilder.Entity("HRPortal.API.Models.EmployeeMaster", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("emp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfJoining")
                        .HasColumnType("date")
                        .HasColumnName("date_of_joining");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("designation");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_id");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("text")
                        .HasColumnName("emergency_contact");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_code");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employment_type");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EmpId");

                    b.ToTable("employee_master");
                });

            modelBuilder.Entity("HRPortal.API.Models.EmployeePersonalDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternateContact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alternate_contact");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blood_group");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<int>("EmpId")
                        .HasColumnType("integer")
                        .HasColumnName("emp_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marital_status");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mobile");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("religion");

                    b.HasKey("Id");

                    b.HasIndex("EmpId")
                        .IsUnique();

                    b.ToTable("employee_personal_details");
                });

            modelBuilder.Entity("HRPortal.API.Models.EmployeePreviousEmployment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<DateOnly?>("DateOfJoining")
                        .HasColumnType("date")
                        .HasColumnName("date_of_joining");

                    b.Property<DateOnly?>("DateOfRelieving")
                        .HasColumnType("date")
                        .HasColumnName("date_of_relieving");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("designation");

                    b.Property<int>("EmpId")
                        .HasColumnType("integer")
                        .HasColumnName("emp_id");

                    b.Property<string>("Experience")
                        .HasColumnType("text")
                        .HasColumnName("experience");

                    b.Property<decimal?>("LastDrawnSalary")
                        .HasColumnType("numeric")
                        .HasColumnName("last_drawn_salary");

                    b.Property<string>("ReasonForLeaving")
                        .HasColumnType("text")
                        .HasColumnName("reason_for_leaving");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.ToTable("employee_previous_employment");
                });

            modelBuilder.Entity("HRPortal.API.Models.HrAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("HrName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hr_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("hr_admins");
                });

            modelBuilder.Entity("HRPortal.API.Models.EmployeeAddress", b =>
                {
                    b.HasOne("HRPortal.API.Models.EmployeeMaster", "Employee")
                        .WithOne("Address")
                        .HasForeignKey("HRPortal.API.Models.EmployeeAddress", "EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRPortal.API.Models.EmployeeCompensation", b =>
                {
                    b.HasOne("HRPortal.API.Models.EmployeeMaster", "Employee")
                        .WithOne()
                        .HasForeignKey("HRPortal.API.Models.EmployeeCompensation", "EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRPortal.API.Models.EmployeeDocuments", b =>
                {
                    b.HasOne("HRPortal.API.Models.EmployeeMaster", "EmployeeMaster")
                        .WithOne("EmployeeDocuments")
                        .HasForeignKey("HRPortal.API.Models.EmployeeDocuments", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeMaster");
                });

            modelBuilder.Entity("HRPortal.API.Models.EmployeeEducation", b =>
                {
                    b.HasOne("HRPortal.API.Models.EmployeeMaster", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRPortal.API.Models.EmployeePersonalDetails", b =>
                {
                    b.HasOne("HRPortal.API.Models.EmployeeMaster", "Employee")
                        .WithOne("PersonalDetails")
                        .HasForeignKey("HRPortal.API.Models.EmployeePersonalDetails", "EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRPortal.API.Models.EmployeePreviousEmployment", b =>
                {
                    b.HasOne("HRPortal.API.Models.EmployeeMaster", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRPortal.API.Models.EmployeeMaster", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("EmployeeDocuments");

                    b.Navigation("PersonalDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
